### ISSUE TITLE
Broken window decoration menu on GNOME

### ISSUE THREAD

**Issue by AKoskovich** [flathub/com.discordapp.DiscordCanary#207]
Forcing Wayland has broken window decoration menus for every GNOME user, please revert. This is because Chromium does not implement it.

**Comment by Nik-mmzd** [comment]
```
~ 
➜ echo $XDG_SESSION_TYPE              
wayland

~ 
➜ xlsclients
Raxacoricofallapatorius  gsd-xsettings
Raxacoricofallapatorius  gpaste-daemon
Raxacoricofallapatorius  mutter-x11-frames
```
I'm using this package with GNOME Wayland right now and see no problems with window decorations: ![image](https://github.com/flathub/com.discordapp.DiscordCanary/assets/19509291/6cfa7ffc-4283-4c46-925a-38831fac9d6a) (GNOME 45/46)

Startup script should enable wayland window decorations if wayland socket exists: https://github.com/flathub/com.discordapp.DiscordCanary/blob/beta/discord-canary.sh#L14


Can you provide more details about your issue?

**Comment by AKoskovich** [comment]
The problem is that if you try and right click on your window decorations, a menu will not pop up, this is because https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:show_window_menu is unimplemented in Chromium. If you switch back to X11 and right click on window decorations you'll see a menu pop up.

There's a couple other misc issues that I've detailed below but the window decoration one is the most prominent: https://github.com/flathub/com.slack.Slack/issues/183#issuecomment-1902686110

**Comment by Nik-mmzd** [comment]
:thinking: OK, I got you.
How critical is that? Based on my experience, most users don't use this menu, and those for whom the lack of the menu is a problem can disable the wayland socket by themselves.
Referensed comment says about
> Window decorations only have a 'close' button, and you cannot right click them to bringup the menu with extra actions

But (as you can see in my screenshot) most of the necessary window action buttons (minimize, maximize, and close) are present in Discord, so the lack of a menu isn't such a big problem.

Disabling wayland socket will bring back xwayland issues, particularly with the nvidia proprietary driver.
Which side should I choose? No menu for GNOME users or xwayland issues for NVIDIA users?

**Comment by AKoskovich** [comment]
Critical is subjective since I personally don't even use the menu (I just use the CTRL + Q hotkey to quit) but IMO there be zero regressions when switching from X11 to Wayland, and currently this is a regression.

Until there are no regressions for the end user (which shouldn't even get determined by Flathub maintainers, Discord should get the final say on that) it should continue to be a user opt in.

Discord Canary is a beta channel of Discord where users test stuff early and report it to Discord. Discord has not enabled Wayland by default in their app, so bug reports resulting from it would be misleading/spam.

> Disabling wayland socket will bring back xwayland issues, particularly with the nvidia proprietary driver.
> Which side should I choose? No menu for GNOME users or xwayland issues for NVIDIA users?

I mean, Flathub maintainers really shouldn't be choosing sides on app behavior. This is an app distribution platform. If it happens on the official .deb it should happen here too.

FYI the explicit sync protocol was just merged for Wayland: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/90 and NVIDIA is looking to implement it, so that will resolve the text issues for Discord w/NVIDIA on Wayland.

**Comment by Nik-mmzd** [comment]
Sounds reasonable.
