### ISSUE TITLE
sync flatpak conf with stable version?

### ISSUE THREAD

**Issue by ahjolinna** [flathub/com.discordapp.DiscordCanary#212]
some flatpak setting like 'xdg.download', "open in default browser" and the wayland opt-in are at least missing currently in this Canary build, it would be nice if these could be also added

**Comment by Nik-mmzd** [comment]
Current `com.discordapp.DiscordCanary.json` is syncronized with com.discordapp.Discord as close as possible.

Wayland support is available, but you're required to enable Wayland socket by yourself, and be aware of regressions: #207 
Some folders permissions were dropped on purpose: #52

**Comment by ahjolinna** [comment]
oh okay, 

about the folder permission thing, why I asked was because drag & drop hasnt been working for me, does with filepicker

**Comment by Nik-mmzd** [comment]
> drag & drop hasnt been working for me

You can add your home folder: `flatpak --user override --filesystem=home com.discordapp.DiscordCanary` to workaround drsg-n-drop, as stated in https://github.com/flathub/com.discordapp.Discord#differences-in-flatpak-version
