### ISSUE TITLE
Application crashes when changing 'Debug Logging' setting

### ISSUE THREAD

**Issue by CorruptComputer** [flathub/com.discordapp.DiscordCanary#35]
In the 'Voice & Video' settings at the very bottom there is one setting called 'Debug Logging' which is enabled by default in Discord Canary. If you disable this and press 'Okay' to restart the client it will crash with 'DiscordCanary killed by SIGTRAP' as the reason given.

**Comment by Nik-mmzd** [comment]
Old issue; seems to be fixed by Discord
