### ISSUE TITLE
Drop org.kde.* when Discord uses Electron >=23.3.0

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.discordapp.DiscordCanary#78]
See https://github.com/flathub/com.discordapp.Discord/issues/324

Current version is

```
Chrome/108.0.5359.215 Electron/22.3.24
```

**Comment by Nik-mmzd** [comment]
It looks like Discord Canary uses Electron 28.2.7 now.

I would appreciate it if someone could test it without `--own-name=org.kde.*`. For some reason, com.discordapp.Discord still [requires it](https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json#L27).

I can't test it myself, as the [AppIndicator and KStatusNotifierItem Support extension](https://extensions.gnome.org/extension/615/appindicator-support/) haven't been updated to GNOME 46.

**Comment by Nik-mmzd** [comment]
I managed to install above extension and test Discord without `--own-name=org.kde.*`. Tray icon seems to be working on GNOME.

**Comment by bbhtt** [comment]
Yea it works now, thanks.
